---
title: "Body Weight_lnCVR"
author: "Hamza"
date: "16 July 2019"
output: word_document
---

```{r load packages, include=FALSE}

library(tidyverse)
library(openxlsx)  
library(knitr)
library(metafor)
library(ggplot2)
```

```{r}
#Calculate Effect Size and run models(lnCVR) for one off exposure

#Body Weight one off
Effect_Size_lnCVR_Body_Weight <- escalc(measure="CVR", m1i=Mean_Treatment, sd1i=SD_Treatment, n1i=Sample_Size_n_Treatment, m2i=Mean_Control, sd2i=SD_Control, n2i=Sample_Size_n_Control, data=Body_Weight)


OF_lnCVR_BW_MA <- rma.mv(yi, vi,random = list(~1|Paper_ID,~1|Cohort_ID), data=Effect_Size_lnCVR_Body_Weight[Effect_Size_lnCVR_Body_Weight$Exposure_Type == "One off",], method = 'REML') 

MG_lnCVR_BW_MA <- rma.mv(yi, vi,random = list(~1|Paper_ID,~1|Cohort_ID), data=Effect_Size_lnCVR_Body_Weight[Effect_Size_lnCVR_Body_Weight$Exposure_Type == "Multigenerational",], method = 'REML')


#Glucose

Effect_Size_Glucose_lnCVR <- escalc(measure="CVR", m1i=Mean_Treatment, sd1i=SD_Treatment, n1i=Sample_Size_n_Treatment, m2i=Mean_Control_Orig, sd2i=SD_Control_Orig, n2i=Sample_Size_n_Control, data=Glucose_Amalgamated) 

OF_lnCVR_Glucose_MA <- rma.mv(yi, vi,random = list(~1|Paper_ID,~1|Cohort_ID), data=Effect_Size_Glucose_lnCVR[Effect_Size_Glucose_lnCVR$Exposure_Type == "One off",], method = 'REML') 

MG_lnCVR_Glucose_MA <- rma.mv(yi, vi,random = list(~1|Paper_ID,~1|Cohort_ID), data=Effect_Size_Glucose_lnCVR[Effect_Size_Glucose_lnCVR$Exposure_Type == "Multigenerational",], method = 'REML') 




#Insulin
Effect_Size_Insulin_lnCVR <- escalc(measure="CVR", m1i=New_Mean__1, sd1i=New_SD__1, n1i=Sample_Size_n_Treatment, m2i=New_Mean, sd2i=New_SD, n2i=Sample_Size_n_Control, data=Insulin_AUC)

OF_lnCVR_Insulin_MA <- rma.mv(yi, vi,random = list(~1|Paper_ID,~1|Cohort_ID), data=Effect_Size_Insulin_lnCVR[Effect_Size_Insulin_lnCVR$Exposure_Type == "One off",], method = 'REML') 

MG_lnCVR_Insulin_MA <- rma.mv(yi, vi,random = list(~1|Paper_ID,~1|Cohort_ID), data=Effect_Size_Insulin_lnCVR[Effect_Size_Insulin_lnCVR$Exposure_Type == "Multigenerational",], method = 'REML') 


#Triglycerides
Effect_Size_TG_lnCVR <- escalc(measure="CVR", m1i=Mean_Treatment, sd1i=SD_Treatment, n1i=Sample_Size_n_Treatment, m2i=Mean_Control_Orig, sd2i=SD_Control_Orig, n2i=Sample_Size_n_Control, data=Triglycerides)

OF_lnCVR_TG_MA <- rma.mv(yi, vi,random = list(~1|Paper_ID,~1|Cohort_ID), data=Effect_Size_TG_lnCVR[Effect_Size_TG_lnCVR$Exposure_Type == "One off",], method = 'REML') 

MG_lnCVR_TG_MA <- rma.mv(yi, vi,random = list(~1|Paper_ID,~1|Cohort_ID), data=Effect_Size_TG_lnCVR[Effect_Size_TG_lnCVR$Exposure_Type == "Multigenerational",], method = 'REML') 


#Adiposity
Effect_Size_Adiposity_lnCVR <- escalc(measure="CVR", m1i=Mean_Treatment, sd1i=SD_Treatment, n1i=Sample_Size_n_Treatment, m2i=Mean_Control_Orig, sd2i=SD_Control_Orig, n2i=Sample_Size_n_Control, data=Adiposity)

OF_lnCVR_Adiposity_MA <- rma.mv(yi, vi,random = list(~1|Paper_ID,~1|Cohort_ID), data=Effect_Size_Adiposity_lnCVR[Effect_Size_Adiposity_lnCVR$Exposure_Type == "One off",], method = 'REML') 

MG_lnCVR_Adiposity_MA <- rma.mv(yi, vi,random = list(~1|Paper_ID,~1|Cohort_ID), data=Effect_Size_Adiposity_lnCVR[Effect_Size_Adiposity_lnCVR$Exposure_Type == "Multigenerational",], method = 'REML')

#Leptin
Effect_Size_Leptin_lnCVR <- escalc(measure="CVR", m1i=Mean_Treatment, sd1i=SD_Treatment, n1i=Sample_Size_n_Treatment, m2i=Mean_Control_Orig, sd2i=SD_Control_Orig, n2i=Sample_Size_n_Control, data=Leptin)

OF_lnCVR_Leptin_MA <- rma.mv(yi, vi,random = list(~1|Paper_ID,~1|Cohort_ID), data=Effect_Size_Leptin_lnCVR[Effect_Size_Leptin_lnCVR$Exposure_Type == "One off",], method = 'REML') 


#Leptin MG
MG_lnCVR_Leptin_MA <- rma.mv(yi, vi,random = list(~1|Paper_ID,~1|Cohort_ID), data=Effect_Size_Leptin_lnCVR[Effect_Size_Leptin_lnCVR$Exposure_Type == "Multigenerational",], method = 'REML') 


```



```{r}
# Making a table of meta-analytic results for ln_CVR

experiment_type <- c(rep("OF", 6), rep("MG", 6))

trait_type <- rep(c("Body_Weight", "Glucose", "Triglycerides", "Insulin", "Adiposity", "Leptin"), 2)  

lnCVR_MA_means <- c(OF_lnCVR_BW_MA$b, OF_lnCVR_Glucose_MA$b, OF_lnCVR_TG_MA$b, OF_lnCVR_Insulin_MA$b, OF_lnCVR_Adiposity_MA$b, OF_lnCVR_Leptin_MA$b, MG_lnCVR_BW_MA$b, MG_lnCVR_Glucose_MA$b, MG_lnCVR_TG_MA$b, MG_lnCVR_Insulin_MA$b, MG_lnCVR_Adiposity_MA$b, MG_lnCVR_Leptin_MA$b)

lnCVR_MA_means

lnCVR_MA_cilb <- c(OF_lnCVR_BW_MA$ci.lb, OF_lnCVR_Glucose_MA$ci.lb, OF_lnCVR_TG_MA$ci.lb, OF_lnCVR_Insulin_MA$ci.lb, OF_lnCVR_Adiposity_MA$ci.lb, OF_lnCVR_Leptin_MA$ci.lb, MG_lnCVR_BW_MA$ci.lb, MG_lnCVR_Glucose_MA$ci.lb, MG_lnCVR_TG_MA$ci.lb, MG_lnCVR_Insulin_MA$ci.lb, MG_lnCVR_Adiposity_MA$ci.lb, MG_lnCVR_Leptin_MA$ci.lb)

lnCVR_MA_cilb

lnCVR_MA_ciub <- c(OF_lnCVR_BW_MA$ci.ub, OF_lnCVR_Glucose_MA$ci.ub, OF_lnCVR_TG_MA$ci.ub, OF_lnCVR_Insulin_MA$ci.ub, OF_lnCVR_Adiposity_MA$ci.ub, OF_lnCVR_Leptin_MA$ci.ub, MG_lnCVR_BW_MA$ci.ub, MG_lnCVR_Glucose_MA$ci.ub, MG_lnCVR_TG_MA$ci.ub, MG_lnCVR_Insulin_MA$ci.ub, MG_lnCVR_Adiposity_MA$ci.ub, MG_lnCVR_Leptin_MA$ci.ub)

lnCVR_MA_ciub

lnCVR_MA_k <- c(OF_lnCVR_BW_MA$k, OF_lnCVR_Glucose_MA$k, OF_lnCVR_TG_MA$k, OF_lnCVR_Insulin_MA$k, OF_lnCVR_Adiposity_MA$k, OF_lnCVR_Leptin_MA$k, MG_lnCVR_BW_MA$k, MG_lnCVR_Glucose_MA$k, MG_lnCVR_TG_MA$k, MG_lnCVR_Insulin_MA$k, MG_lnCVR_Adiposity_MA$k, MG_lnCVR_Leptin_MA$k)

lnCVR_MA_k

length(OF_lnCVR_BW_MA$s.levels[1][[1]])

lnCVR_MA_Npapers <- c(length(OF_lnCVR_BW_MA$s.levels[1][[1]]), 
                     length(OF_lnCVR_Glucose_MA$s.levels[1][[1]]),
                     length(OF_lnCVR_TG_MA$s.levels[1][[1]]),
                     length(OF_lnCVR_Insulin_MA$s.levels[1][[1]]),
                     length(OF_lnCVR_Adiposity_MA$s.levels[1][[1]]),
                     length(OF_lnCVR_Leptin_MA$s.levels[1][[1]]),
                     length(MG_lnCVR_BW_MA$s.levels[1][[1]]),
                     length(MG_lnCVR_Glucose_MA$s.levels[1][[1]]),
                     length(MG_lnCVR_TG_MA$s.levels[1][[1]]),
                     length(MG_lnCVR_Insulin_MA$s.levels[1][[1]]),
                     length(MG_lnCVR_Adiposity_MA$s.levels[1][[1]]),
                     length(MG_lnCVR_Leptin_MA$s.levels[1][[1]])
                     )
                     
lnCVR_MA_Npapers

lnCVR_MA_Ncohorts <- c(length(OF_lnCVR_BW_MA$s.levels[2][[1]]), 
                     length(OF_lnCVR_Glucose_MA$s.levels[2][[1]]),
                     length(OF_lnCVR_TG_MA$s.levels[2][[1]]),
                     length(OF_lnCVR_Insulin_MA$s.levels[2][[1]]),
                     length(OF_lnCVR_Adiposity_MA$s.levels[2][[1]]),
                     length(OF_lnCVR_Leptin_MA$s.levels[2][[1]]),
                     length(MG_lnCVR_BW_MA$s.levels[2][[1]]),
                     length(MG_lnCVR_Glucose_MA$s.levels[2][[1]]),
                     length(MG_lnCVR_TG_MA$s.levels[2][[1]]),
                     length(MG_lnCVR_Insulin_MA$s.levels[2][[1]]),
                     length(MG_lnCVR_Adiposity_MA$s.levels[2][[1]]),
                     length(MG_lnCVR_Leptin_MA$s.levels[2][[1]])
                     )
                     
lnCVR_MA_Ncohorts  

#create data fame
lnCVR_MA_results <- data.frame(Experiment_type = experiment_type, trait = trait_type, mean = lnCVR_MA_means, ci.lb= lnCVR_MA_cilb, ci.ub= lnCVR_MA_ciub, k= lnCVR_MA_k, N_papers = lnCVR_MA_Npapers, N_cohorts=lnCVR_MA_Ncohorts)

lnCVR_MA_results

lnCVR_MA_results <- unite(lnCVR_MA_results, "labels", c("Experiment_type", "trait"), sep = " - ", remove = FALSE)

lnCVR_MA_results

#Plotting

plot_lnCVR <- ggplot(lnCVR_MA_results, aes(x=trait, y=mean, colour=Experiment_type)) + 
  geom_errorbar(aes(ymin=ci.lb, ymax=ci.ub), width = 0, position = position_dodge(0.3)) +
  geom_point(aes(x = trait, y = mean), position = position_dodge(0.3))+
  geom_hline(yintercept = 0, lty = "dotted") +
  labs(title ="Difference between treatment and control in variation", x = "Traits", y = "lnCVR") +
  coord_flip()
 
plot_lnCVR

ggsave("../figs/plot_lnCVR.png")

```





