---
title: "Results (Plots)"
author: "Hamza"
date: "8 January 2020"
output:
  pdf_document: default
  html_document: default
editor_options: 
  chunk_output_type: inline
---

```{r load packages, include=FALSE, message=FALSE, warning=FALSE}
#install.packages("devtools")
#install.packages("tidyverse")
#install.packages("metafor")
#install.packages("patchwork")
#install.packages("R.rsp")
#install.packages("cowplot")
#install.packages("ggpubr")
#install.packages("extrafont")


#devtools::install_github("itchyshin/orchard_plot", subdir = "orchaRd", force = TRUE, build_vignettes = TRUE)

#font_import() #importing fonts
#loadfonts() #loading fonts
library(extrafontdb)
extrafont::loadfonts(device="win")
library(tidyverse)
library(openxlsx)  
library(knitr)
library(metafor)
library(ggplot2)
library(readxl)
library(orchaRd)
library(patchwork)
library(tidyverse)
library(cowplot)
library(ggpubr)
#Install miktex and then run this to knit a pdf file
#install.packages('tinytex')
#tinytex::install_tinytex()
```
PLOTS WILL ONLY WORK WITH INTERCEPT MODELS !!! Add in the intercept models here to run before the plots are produced

### Question 1 - Exposure Type (used as a moderator)
```{r}
#lnRR One off
All_Data_Analysis_OF <- rma.mv(yi, VmatCVR_OF, random = list(~1|Trait, ~1|Paper_ID,~1|Cohort_ID,~1|ES_ID), data=OF_ALL, method = 'REML')

summary(All_Data_Analysis_OF)

Overall_Exposure_Type_orchard_OF <- orchard_plot(All_Data_Analysis_OF_int, mod = "Exposure_Type", xlab = "lnRR", transfm = "none", angle = 45)+
  scale_colour_manual(values=c("#56B4E9"))+ 
  scale_fill_manual(values=c("#999999"))+
  labs(title="A",
       subtitle = "Differences in means between control and treatment groups" )+
  scale_x_continuous(breaks = seq(-3, 4, by = 0.5))
Overall_Exposure_Type_orchard_OF

#lnRR MG
All_Data_Analysis_MG <- rma.mv(yi, VmatCVR_MG, random = list(~1|Trait, ~1|Paper_ID,~1|Cohort_ID,~1|ES_ID), data=MG_ALL, method = 'REML')

summary(All_Data_Analysis_MG)

Overall_Exposure_Type_orchard_MG <- orchard_plot(All_Data_Analysis_MG, mod = "Multigenerational", xlab = "lnRR", transfm = "none", angle = 45)+
  scale_colour_manual(values=c("#E69F00"))+
  scale_fill_manual(values=c("#999999"))+
  scale_x_continuous(breaks = seq(-3, 4, by = 0.5))
Overall_Exposure_Type_orchard_MG

#lnCVR One off
Overall_Exposure_Type_orchard_OF_lnCVR <- orchard_plot(All_Data_Analysis_OF_lnCVR, mod = "Exposure_Type", xlab = "lnCVR", transfm = "none", angle =45)+
  scale_colour_manual(values=c("#56B4E9"))+
  scale_fill_manual(values=c("#999999"))+
  labs(title = "B",
       subtitle = "Differences in variance between control and treatment groups")+
  scale_x_continuous(breaks = seq(-3, 4, by = 0.5))
Overall_Exposure_Type_orchard_OF_lnCVR

#lnCVR MG
Overall_Exposure_Type_orchard_MG_lnCVR <- orchard_plot(All_Data_Analysis_MG_lnCVR, mod = "Exposure_Type", xlab = "lnCVR", transfm = "none", angle =45)+
  scale_colour_manual(values=c("#E69F00"))+
  scale_fill_manual(values=c("#999999"))+
  labs(title = "B",
       subtitle = "Differences in variance between control and treatment groups")+
  scale_x_continuous(breaks = seq(-3, 4, by = 0.5))
Overall_Exposure_Type_orchard_MG_lnCVR


#Joining Plots 

Overall_Exp_Type_orchard_joined_lnRR <- Overall_Exposure_Type_orchard_OF/Overall_Exposure_Type_orchard_MG
Overall_Exp_Type_orchard_joined_lnRR

Overall_Exp_Type_orchard_joined_lnCVR <- Overall_Exposure_Type_orchard_OF_lnCVR/Overall_Exposure_Type_orchard_MG_lnCVR
Overall_Exp_Type_orchard_joined_lnCVR

#Saving plots
#setwd if I really want to save in Plots folder

# ggsave("Overall.pdf", width = 16, height = 20, units = "cm", device = cairo_pdf)
# 
# ggsave("Overall.jpg", width = 16, height = 20, units = "cm")


 
```



### Question 2 and 3 - Parental Sex and Offspring Sex
```{r}
#MG F0 lnRR
All_Traits_Analysis_0mods_MG_f0_orchard <- orchard_plot(All_Traits_Analysis_0mods_MG_f0, mod = "F0_Parent_Exposed", xlab = "lnRR", transfm = "none")+
  scale_colour_manual(values=c("#E69F00","#E69F00"))+
   scale_fill_manual(values=c("#999999","#999999"))+
  labs(title = "E",
  subtitle = "Multigenerational")+
  theme(plot.subtitle=element_text(face = 'bold', colour="#E69F00")) +
   xlim(-1,4)
  
All_Traits_Analysis_0mods_MG_f0_orchard
#OF F0 lnRR
All_Traits_Analysis_0mods_OF_f0_orchard <- orchard_plot(All_Traits_Analysis_0mods_OF_f0, mod = "F0_Parent_Exposed", xlab = "lnRR", transfm = "none")+
  scale_colour_manual(values=c("#56B4E9","#56B4E9","#56B4E9"))+
   scale_fill_manual(values=c("#999999","#999999","#999999"))+
  labs(title = "C",
  subtitle = "One off")+
  theme(plot.subtitle=element_text(face = 'bold', colour="#56B4E9"))+
  xlim(-1,4)
All_Traits_Analysis_0mods_OF_f0_orchard

#MG Sex lnRR
All_Traits_Analysis_0mods_MG_sex_orchard <- orchard_plot(All_Traits_Analysis_0mods_MG_sex, mod = "Sex", xlab = "lnRR", transfm = "none")+
  scale_colour_manual(values=c("#E69F00","#E69F00","#E69F00"))+
   scale_fill_manual(values=c("#999999","#999999","#999999"))+
  labs(title = "I",
  subtitle = "Multigenerational")+
  theme(plot.subtitle=element_text(face = 'bold', colour="#E69F00")) 
All_Traits_Analysis_0mods_MG_sex_orchard

#OF Sex lnRR
All_Traits_Analysis_0mods_OF_sex_orchard <- orchard_plot(All_Traits_Analysis_0mods_OF_sex, mod = "Sex", xlab = "lnRR", transfm = "none")+
  scale_colour_manual(values=c("#56B4E9","#56B4E9","#56B4E9"))+
   scale_fill_manual(values=c("#999999","#999999","#999999"))+
  labs(title = "G",
  subtitle = "One off")+
  theme(plot.subtitle=element_text(face = 'bold', colour="#56B4E9"))+
  xlim(-1,4) 
All_Traits_Analysis_0mods_OF_sex_orchard


#MG F0 lnCVR
All_Traits_Analysis_0mods_MG_f0_orchard_lnCVR <- orchard_plot(All_Traits_Analysis_0mods_MG_f0_lnCVR, mod = "F0_Parent_Exposed", xlab = "lnCVR", transfm = "none")+
  scale_colour_manual(values=c("#E69F00","#E69F00"))+
   scale_fill_manual(values=c("#999999","#999999"))+
  labs(title = "F",
  subtitle = "Multigenerational")+
  theme(plot.subtitle=element_text(face = 'bold', colour="#E69F00")) 
All_Traits_Analysis_0mods_MG_f0_orchard_lnCVR
#OF F0 lnCVR
All_Traits_Analysis_0mods_OF_f0_orchard_lnCVR <- orchard_plot(All_Traits_Analysis_0mods_OF_f0_lnCVR, mod = "F0_Parent_Exposed", xlab = "lnCVR", transfm = "none")+
  scale_colour_manual(values=c("#56B4E9","#56B4E9","#56B4E9"))+
   scale_fill_manual(values=c("#999999","#999999","#999999"))+
  labs(title = "D",
  subtitle = "One off")+
  theme(plot.subtitle=element_text(face = 'bold', colour="#56B4E9")) 
All_Traits_Analysis_0mods_OF_f0_orchard_lnCVR

#MG Sex lnCVR
All_Traits_Analysis_0mods_MG_sex_orchard_lnCVR <- orchard_plot(All_Traits_Analysis_0mods_MG_sex_lnCVR, mod = "Sex", xlab = "lnCVR", transfm = "none")+
  scale_colour_manual(values=c("#E69F00","#E69F00","#E69F00"))+
   scale_fill_manual(values=c("#999999","#999999","#999999"))+
  labs(title = "J",
  subtitle = "Multigenerational")+
  theme(plot.subtitle=element_text(face = 'bold', colour="#E69F00")) +
  theme(                                # Everything from here onwards edits the legend
legend.position = c(0.05, 0.99),
legend.justification = c(0, 1),
legend.key.size = unit(1, "mm")) +
theme(
legend.direction = "horizontal",
legend.title = element_text(size = 8),
legend.text = element_text(size = 10)) +
scale_x_continuous(expand = c(0.1, 0.1)) 
All_Traits_Analysis_0mods_MG_sex_orchard_lnCVR

#OF Sex lnCVR
All_Traits_Analysis_0mods_OF_sex_orchard_lnCVR <- orchard_plot(All_Traits_Analysis_0mods_OF_sex_lnCVR, mod = "Sex", xlab = "lnCVR", transfm = "none")+
  scale_colour_manual(values=c("#56B4E9","#56B4E9","#56B4E9"))+
   scale_fill_manual(values=c("#999999","#999999","#999999"))+
  labs(title = "H",
  subtitle = "One off")+
  theme(plot.subtitle=element_text(face = 'bold', colour="#56B4E9")) +
  xlim(-3,2)
  #theme(                                # Everything from here onwards edits the legend
#legend.position = c(0.05, 0.99),
#legend.justification = c(0, 1),
#legend.key.size = unit(1, "mm")) +
#theme(
#legend.direction = "horizontal",
#legend.title = element_text(size = 8),
#legend.text = element_text(size = 10)) +
#scale_x_continuous(expand = c(0.1, 0.1))
All_Traits_Analysis_0mods_OF_sex_orchard_lnCVR
```

### Joining Plots - Exposed Sex F0
```{r}
Exposed_Sex_F0_Joined <- All_Traits_Analysis_0mods_OF_f0_orchard + All_Traits_Analysis_0mods_OF_f0_orchard_lnCVR + All_Traits_Analysis_0mods_MG_f0_orchard +  All_Traits_Analysis_0mods_MG_f0_orchard_lnCVR + plot_layout(ncol=2,nrow = 2)

Final_Exposed_F0 <- Exposed_Sex_F0_Joined + plot_annotation(
  title = 'Exposed Sex (F0)',
  theme = theme(plot.title = element_text(size = 30, family = "Garamond", face='bold')))
 


Final_Exposed_F0

ggsave("Exposed_F0.pdf", width = 20, height = 20, units = "cm", device = cairo_pdf)
ggsave("Exposed_F0.jpg", width = 20, height = 20, units = "cm")


```

### Joining plots - Grand offspring Sex

```{r}
Sex_Joined <- All_Traits_Analysis_0mods_OF_sex_orchard + All_Traits_Analysis_0mods_OF_sex_orchard_lnCVR + All_Traits_Analysis_0mods_MG_sex_orchard + All_Traits_Analysis_0mods_MG_sex_orchard_lnCVR + plot_layout(ncol=2,nrow = 2) 


Final_Sex <- Sex_Joined + plot_annotation(
  title = 'Grand offspring Sex',
  theme = theme(plot.title = element_text(size = 30, family = "Garamond", face='bold')))
 

Final_Sex

ggsave("Sex.pdf", width = 20, height = 20, units = "cm", device = cairo_pdf)
ggsave("Sex.jpg", width = 20, height = 20, units = "cm")
```




### Question 4 - Traits
```{r}
#Sample Sizes Multigenerational and One off

#MG_ALL$N <- rowSums(MG_ALL[, c("Sample_Size_n_Control", "Sample_Size_n_Treatment")])

#OF_ALL$N <- rowSums(OF_ALL[, c("Sample_Size_n_Control", "Sample_Size_n_Treatment")])

#MG Trats lnRR

Traits_Analysis_MG_orchard <- orchard_plot(Traits_Analysis_MG, mod = "Trait", xlab = "lnRR", transfm = "none", angle = 45)+
  scale_colour_manual(values=c("#E69F00","#E69F00","#E69F00","#E69F00","#E69F00","#E69F00","#E69F00","#E69F00"))+
   scale_fill_manual(values=c("#999999","#999999","#999999","#999999","#999999","#999999","#999999","#999999"))+
  labs(title = "M",
  subtitle = "Multigenerational")+
  theme(plot.subtitle=element_text(face = 'bold', colour="#E69F00")) 
Traits_Analysis_MG_orchard

#OF Trats lnRR
Traits_Analysis_OF_orchard <- orchard_plot(Traits_Analysis_OF, mod = "Trait", xlab = "lnRR", transfm = "none", angle = 45)+
  scale_colour_manual(values=c("#56B4E9","#56B4E9","#56B4E9","#56B4E9","#56B4E9","#56B4E9","#56B4E9","#56B4E9"))+
   scale_fill_manual(values=c("#999999","#999999","#999999","#999999","#999999","#999999","#999999","#999999"))+
  labs(title = "K",
  subtitle = "One off")+
  theme(plot.subtitle=element_text(face = 'bold', colour="#56B4E9")) +
  xlim(-1,4)
Traits_Analysis_OF_orchard

#MG Trats lnCVR

Traits_Analysis_MG_orchard_lnCVR <- orchard_plot(Traits_Analysis_MG_lnCVR, mod = "Trait", xlab = "lnCVR", transfm = "none", angle = 45)+
  scale_colour_manual(values=c("#E69F00","#E69F00","#E69F00","#E69F00","#E69F00","#E69F00","#E69F00","#E69F00"))+
   scale_fill_manual(values=c("#999999","#999999","#999999","#999999","#999999","#999999","#999999","#999999"))+
  labs(title = "N",
  subtitle = "Multigenerational")+
  theme(plot.subtitle=element_text(face = 'bold', colour="#E69F00")) +
   theme(                                # Everything from here onwards edits the legend
legend.position = c(0.05, 0.99),
legend.justification = c(0, 1),
legend.key.size = unit(1, "mm")) +
theme(
legend.direction = "horizontal",
legend.title = element_text(size = 8),
legend.text = element_text(size = 10)) +
scale_x_continuous(expand = c(0.1, 0.1))
Traits_Analysis_MG_orchard_lnCVR

#OF Trats lnCVR
Traits_Analysis_OF_orchard_lnCVR <- orchard_plot(Traits_Analysis_OF_lnCVR, mod = "Trait", xlab = "lnCVR", transfm = "none", angle = 45)+
  scale_colour_manual(values=c("#56B4E9","#56B4E9","#56B4E9","#56B4E9","#56B4E9","#56B4E9","#56B4E9","#56B4E9"))+
   scale_fill_manual(values=c("#999999","#999999","#999999","#999999","#999999","#999999","#999999","#999999"))+
  labs(title = "L",
  subtitle = "One off")+
  theme(plot.subtitle=element_text(face = 'bold', colour="#56B4E9")) +
   theme(                                # Everything from here onwards edits the legend
legend.position = c(0.05, 0.99),
legend.justification = c(0, 1),
legend.key.size = unit(1, "mm")) +
theme(
legend.direction = "horizontal",
legend.title = element_text(size = 8),
legend.text = element_text(size = 10)) +
scale_x_continuous(expand = c(0.1, 0.1))+
  xlim(-3,2)
Traits_Analysis_OF_orchard_lnCVR
```

### Joining Traits

```{r}
Traits_Final <- Traits_Analysis_OF_orchard + Traits_Analysis_OF_orchard_lnCVR + Traits_Analysis_MG_orchard + Traits_Analysis_MG_orchard_lnCVR + plot_layout(ncol=2,nrow = 2)

Traits_Final

```




