---
title: "Glucose_Analysis"
author: "Hamza"
date: "2 October 2019"
output:
  pdf_document: default
  html_document: default
---

## Meta-regression Glucose

```{r load packages, include=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(openxlsx)  
library(knitr)
library(metafor)
library(ggplot2)
library(readxl)
```

```{r}
load(file="Effect_Size_All_Traits.RData")
load(file="Effect_Size_All_Traits_lnCVR.RData")
#lnRR
Glucose_FBG_lnRR <- subset(Effect_Size_All_Traits, Effect_Size_All_Traits$Trait == "Glucose_FBG")
Glucose_TT_lnRR<- subset(Effect_Size_All_Traits, Effect_Size_All_Traits$Trait == "Glucose_TT")

Glucose_FBG_lnRR_MG <- subset(Glucose_FBG_lnRR, Glucose_FBG_lnRR$Exposure_Type == "Multigenerational")
Glucose_TT_lnRR_MG <- subset(Glucose_TT_lnRR, Glucose_TT_lnRR$Exposure_Type == "Multigenerational")

Glucose_FBG_lnRR_OF <- subset(Glucose_FBG_lnRR, Glucose_FBG_lnRR$Exposure_Type == "One off")
Glucose_TT_lnRR_OF <- subset(Glucose_TT_lnRR, Glucose_TT_lnRR$Exposure_Type == "One off")

#lnCVR
Glucose_FBG_lnCVR <- subset(Effect_Size_All_Traits_lnCVR, Effect_Size_All_Traits_lnCVR$Trait == "Glucose_FBG")
Glucose_TT_lnCVR<- subset(Effect_Size_All_Traits_lnCVR, Effect_Size_All_Traits_lnCVR$Trait == "Glucose_TT")

Glucose_FBG_lnCVR_MG <- subset(Glucose_FBG_lnCVR, Glucose_FBG_lnCVR$Exposure_Type == "Multigenerational")
Glucose_TT_lnCVR_MG <- subset(Glucose_TT_lnCVR, Glucose_TT_lnCVR$Exposure_Type == "Multigenerational")

Glucose_FBG_lnCVR_OF <- subset(Glucose_FBG_lnCVR, Glucose_FBG_lnCVR$Exposure_Type == "One off")
Glucose_TT_lnCVR_OF <- subset(Glucose_TT_lnCVR, Glucose_TT_lnCVR$Exposure_Type == "One off")
 
```

#FBG Analysis (Overall and then split by exposure type)
```{r}

Glucose_overall_lnRR_FBG <- rma.mv(yi, vi, random = list(~1|ES_ID,~1|Cohort_ID), data=Glucose_FBG_lnRR, method = 'REML')

summary(Glucose_overall_lnRR_FBG)
funnel(Glucose_overall_lnRR_FBG,yaxis="seinv")

#Tibble of overall results

Glucose_overall_lnRR_FBG <- tibble(
  ID = "Overall", 
  lnRR = Glucose_overall_lnRR_FBG$b[1],
  ci.lb = Glucose_overall_lnRR_FBG$ci.lb[1],
  ci.ub = Glucose_overall_lnRR_FBG$ci.ub[1]
)

plot_Glucose_overall_FBG <- ggplot(Glucose_overall_lnRR_FBG, aes(x=ID, y=lnRR)) + 
  geom_errorbar(aes(ymin=ci.lb, ymax=ci.ub), width = 0.05, position = position_dodge(0.3)) +
  geom_point(aes(x = ID, y = lnRR), position = position_dodge(0.3))+
  geom_hline(yintercept = 0, lty = "dotted") +
  labs(x = "ID", y = "lnRR") +
  coord_flip()
plot_Glucose_overall_FBG

#Split by exposure type

Glucose_overall_lnRR_FBG_MG <- rma.mv(yi, vi, random = list(~1|ES_ID,~1|Cohort_ID), data=Glucose_FBG_lnRR_MG, method = 'REML')

summary(Glucose_overall_lnRR_FBG_MG)
funnel(Glucose_overall_lnRR_FBG_MG,yaxis="seinv")

Glucose_overall_lnRR_FBG_OF <- rma.mv(yi, vi, random = list(~1|ES_ID,~1|Cohort_ID), data=Glucose_FBG_lnRR_OF, method = 'REML')

summary(Glucose_overall_lnRR_FBG_OF)
funnel(Glucose_overall_lnRR_FBG_OF,yaxis="seinv")
k_exp <- Glucose_FBG_lnRR_OF %>% group_by(Exposure_Type) %>% count()
k_exp


Glucose_FBG_Exp_lnRR <- tibble(
  Exposure_Type = c("Multigenertional","One off"),
  lnRR = c(Glucose_overall_lnRR_FBG_MG$b[1],Glucose_overall_lnRR_FBG_OF$b[1]),
  ci.lb = c(Glucose_overall_lnRR_FBG_MG$ci.lb[1],Glucose_overall_lnRR_FBG_OF$ci.lb[1]),
  ci.ub = c(Glucose_overall_lnRR_FBG_MG$ci.ub[1],Glucose_overall_lnRR_FBG_OF$ci.ub[1])
)

Glucose_FBG_Exp_lnRR



#Plotting when split by exp type

plot_Glucose_FBG_exp_type <- ggplot(Glucose_FBG_Exp_lnRR, aes(x=Exposure_Type, y=lnRR, colour = Exposure_Type)) + 
  geom_errorbar(aes(ymin=ci.lb, ymax=ci.ub), width = 0.05, position = position_dodge(0.3)) +
  geom_point(aes(x = Exposure_Type, y = lnRR), position = position_dodge(0.3))+
  geom_hline(yintercept = 0, lty = "dotted") +
  labs(x = "Exp_Type", y = "lnRR") +
  coord_flip()
plot_Glucose_FBG_exp_type
```

#Tolerance test analysis (Overall and then split by exposure type)

```{r}

Glucose_overall_lnRR_TT <- rma.mv(yi, vi, random = list(~1|ES_ID,~1|Cohort_ID), data=Glucose_TT_lnRR, method = 'REML')

summary(Glucose_overall_lnRR_TT)
funnel(Glucose_overall_lnRR_TT,yaxis="seinv")

#Tibble of overall results

Glucose_overall_lnRR_TT <- tibble(
  ID = "Overall", 
  lnRR = Glucose_overall_lnRR_TT$b[1],
  ci.lb = Glucose_overall_lnRR_TT$ci.lb[1],
  ci.ub = Glucose_overall_lnRR_TT$ci.ub[1]
)

plot_Glucose_overall_TT <- ggplot(Glucose_overall_lnRR_TT, aes(x=ID, y=lnRR)) + 
  geom_errorbar(aes(ymin=ci.lb, ymax=ci.ub), width = 0.05, position = position_dodge(0.3)) +
  geom_point(aes(x = ID, y = lnRR), position = position_dodge(0.3))+
  geom_hline(yintercept = 0, lty = "dotted") +
  labs(x = "ID", y = "lnRR") +
  coord_flip()
plot_Glucose_overall_TT

#Split by exposure type

Glucose_overall_lnRR_TT_MG <- rma.mv(yi, vi, random = list(~1|ES_ID,~1|Cohort_ID), data=Glucose_TT_lnRR_MG, method = 'REML')

summary(Glucose_overall_lnRR_TT_MG)
funnel(Glucose_overall_lnRR_TT_MG)

Glucose_overall_lnRR_TT_OF <- rma.mv(yi, vi, random = list(~1|ES_ID,~1|Cohort_ID), data=Glucose_TT_lnRR_OF, method = 'REML')

summary(Glucose_overall_lnRR_TT_OF)
k_exp <- Glucose_TT_lnRR_OF %>% group_by(Exposure_Type) %>% count()
k_exp


funnel(Glucose_overall_lnRR_TT_OF)

Glucose_TT_Exp_lnRR <- tibble(
  Exposure_Type = c("Multigenerational","One off"),
  lnRR = c(Glucose_overall_lnRR_TT_MG$b[1],Glucose_overall_lnRR_TT_OF$b[1]),
  ci.lb = c(Glucose_overall_lnRR_TT_MG$ci.lb[1],Glucose_overall_lnRR_TT_OF$ci.lb[1]),
  ci.ub = c(Glucose_overall_lnRR_TT_MG$ci.ub[1],Glucose_overall_lnRR_TT_OF$ci.ub[1])
)

Glucose_TT_Exp_lnRR



#Plotting when split by exp type

plot_Glucose_TT_exp_type <- ggplot(Glucose_TT_Exp_lnRR, aes(x=Exposure_Type, y=lnRR, colour = Exposure_Type)) + 
  geom_errorbar(aes(ymin=ci.lb, ymax=ci.ub), width = 0.05, position = position_dodge(0.3)) +
  geom_point(aes(x = Exposure_Type, y = lnRR), position = position_dodge(0.3))+
  geom_hline(yintercept = 0, lty = "dotted") +
  labs(x = "Exp_Type", y = "lnRR") +
  coord_flip()
plot_Glucose_TT_exp_type
```

#FBG Analysis (lnCVR)
```{r}
Glucose_overall_lnCVR_FBG <- rma.mv(yi, vi, random = list(~1|ES_ID,~1|Cohort_ID), data=Glucose_FBG_lnCVR, method = 'REML')

summary(Glucose_overall_lnCVR_FBG)
funnel(Glucose_overall_lnCVR_FBG)

#Tibble of overall results

Glucose_overall_lnCVR_FBG <- tibble(
  ID = "Overall", 
  lnCVR = Glucose_overall_lnCVR_FBG$b[1],
  ci.lb = Glucose_overall_lnCVR_FBG$ci.lb[1],
  ci.ub = Glucose_overall_lnCVR_FBG$ci.ub[1]
)

plot_Glucose_overall_FBG_lnCVR <- ggplot(Glucose_overall_lnCVR_FBG, aes(x=ID, y=lnCVR)) + 
  geom_errorbar(aes(ymin=ci.lb, ymax=ci.ub), width = 0, position = position_dodge(0.3)) +
  geom_point(aes(x = ID, y = lnCVR), position = position_dodge(0.3))+
  geom_hline(yintercept = 0, lty = "dotted") +
  labs(x = "ID", y = "lnCVR") +
  coord_flip()
plot_Glucose_overall_FBG_lnCVR

#Split by exposure type

Glucose_overall_lnCVR_FBG_MG <- rma.mv(yi, vi, random = list(~1|ES_ID,~1|Cohort_ID), data=Glucose_FBG_lnCVR_MG, method = 'REML')

summary(Glucose_overall_lnCVR_FBG_MG)
funnel(Glucose_overall_lnCVR_FBG_MG)

Glucose_overall_lnCVR_FBG_OF <- rma.mv(yi, vi, random = list(~1|ES_ID,~1|Cohort_ID), data=Glucose_FBG_lnCVR_OF, method = 'REML')

summary(Glucose_overall_lnCVR_FBG_OF)
funnel(Glucose_overall_lnCVR_FBG_OF)

Glucose_FBG_Exp_lnCVR <- tibble(
  Exposure_Type = c("Multigenerational", "One off"),
  lnCVR = c(Glucose_overall_lnCVR_FBG_MG$b[1],Glucose_overall_lnCVR_FBG_OF$b[1]),
  ci.lb = c(Glucose_overall_lnCVR_FBG_MG$ci.lb[1],Glucose_overall_lnCVR_FBG_OF$ci.lb[1]),
  ci.ub = c(Glucose_overall_lnCVR_FBG_MG$ci.ub[1],Glucose_overall_lnCVR_FBG_OF$ci.ub[1])
)

Glucose_FBG_Exp_lnCVR



#Plotting when split by exp type

plot_Glucose_FBG_exp_type_lnCVR <- ggplot(Glucose_FBG_Exp_lnCVR, aes(x=Exposure_Type, y=lnCVR, colour = Exposure_Type)) + 
  geom_errorbar(aes(ymin=ci.lb, ymax=ci.ub), width = 0.05, position = position_dodge(0.3)) +
  geom_point(aes(x = Exposure_Type, y = lnCVR), position = position_dodge(0.3))+
  geom_hline(yintercept = 0, lty = "dotted") +
  labs(x = "Exp_Type", y = "lnCVR") +
  coord_flip()
plot_Glucose_FBG_exp_type_lnCVR
```

#Tolerance test analysis (lnCVR)
```{r}

Glucose_overall_lnCVR_TT <- rma.mv(yi, vi, random = list(~1|ES_ID,~1|Cohort_ID), data=Glucose_TT_lnCVR, method = 'REML')

summary(Glucose_overall_lnCVR_TT)
funnel(Glucose_overall_lnCVR_TT)

#Tibble of overall results

Glucose_overall_lnCVR_TT <- tibble(
  ID = "Overall", 
  lnCVR = Glucose_overall_lnCVR_TT$b[1],
  ci.lb =Glucose_overall_lnCVR_TT$ci.lb[1] ,
  ci.ub =Glucose_overall_lnCVR_TT$ci.ub[1] 
)

plot_Glucose_overall_TT_lnCVR <- ggplot(Glucose_overall_lnCVR_TT, aes(x=ID, y=lnCVR)) + 
  geom_errorbar(aes(ymin=ci.lb, ymax=ci.ub), width = 0, position = position_dodge(0.3)) +
  geom_point(aes(x = ID, y = lnCVR), position = position_dodge(0.3))+
  geom_hline(yintercept = 0, lty = "dotted") +
  labs(x = "ID", y = "lnCVR") +
  coord_flip()
plot_Glucose_overall_TT_lnCVR

#Split by exposure type

Glucose_overall_lnCVR_TT_MG <- rma.mv(yi, vi, random = list(~1|ES_ID,~1|Cohort_ID), data=Glucose_TT_lnCVR_MG, method = 'REML')

summary(Glucose_overall_lnCVR_TT_MG)
funnel(Glucose_overall_lnCVR_TT_MG)

Glucose_overall_lnCVR_TT_OF <- rma.mv(yi, vi, random = list(~1|ES_ID,~1|Cohort_ID), data=Glucose_TT_lnCVR_OF, method = 'REML')

summary(Glucose_overall_lnCVR_TT_OF)
funnel(Glucose_overall_lnCVR_TT_OF)

Glucose_TT_Exp_lnCVR <- tibble(
  Exposure_Type = c("Multigenerational", "One off"),
  lnCVR = c(Glucose_overall_lnCVR_TT_MG$b[1],Glucose_overall_lnCVR_TT_OF$b[1]),
  ci.lb = c(Glucose_overall_lnCVR_TT_MG$ci.lb[1],Glucose_overall_lnCVR_TT_OF$ci.lb[1]),
  ci.ub = c(Glucose_overall_lnCVR_TT_MG$ci.ub[1],Glucose_overall_lnCVR_TT_OF$ci.ub[1])
)

Glucose_TT_Exp_lnCVR



#Plotting when split by exp type

plot_Glucose_TT_exp_type_lnCVR <- ggplot(Glucose_TT_Exp_lnCVR, aes(x=Exposure_Type, y=lnCVR, colour = Exposure_Type)) + 
  geom_errorbar(aes(ymin=ci.lb, ymax=ci.ub), width = 0.05, position = position_dodge(0.3)) +
  geom_point(aes(x = Exposure_Type, y = lnCVR), position = position_dodge(0.3))+
  geom_hline(yintercept = 0, lty = "dotted") +
  labs(x = "Exp_Type", y = "lnCVR") +
  coord_flip()
plot_Glucose_TT_exp_type_lnCVR
```


