---
title: "Insulin"
author: "Hamza"
date: "2 October 2019"
output:
  pdf_document: default
  html_document: default
---
## Meta-regression Insulin

```{r load packages, include=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(openxlsx)  
library(knitr)
library(metafor)
library(ggplot2)
library(readxl)
```

```{r}
load(file="Effect_Size_All_Traits.RData")
load(file="Effect_Size_All_Traits_lnCVR.RData")
#lnRR
Insulin_FI_lnRR <- subset(Effect_Size_All_Traits, Effect_Size_All_Traits$Trait == "Insulin_FI")
Insulin_TT_lnRR<- subset(Effect_Size_All_Traits, Effect_Size_All_Traits$Trait == "Insulin_TT")

Insulin_FI_lnRR_MG <- subset(Insulin_FI_lnRR, Insulin_FI_lnRR$Exposure_Type == "Multigenerational")
Insulin_TT_lnRR_MG <- subset(Insulin_TT_lnRR, Insulin_TT_lnRR$Exposure_Type == "Multigenerational")

Insulin_FI_lnRR_OF <- subset(Insulin_FI_lnRR, Insulin_FI_lnRR$Exposure_Type == "One off")
Insulin_TT_lnRR_OF <- subset(Insulin_TT_lnRR, Insulin_TT_lnRR$Exposure_Type == "One off")

#lnCVR
Insulin_FI_lnCVR <- subset(Effect_Size_All_Traits_lnCVR, Effect_Size_All_Traits_lnCVR$Trait == "Insulin_FI")
Insulin_TT_lnCVR<- subset(Effect_Size_All_Traits_lnCVR, Effect_Size_All_Traits_lnCVR$Trait == "Insulin_TT")

Insulin_FI_lnCVR_MG <- subset(Insulin_FI_lnCVR, Insulin_FI_lnCVR$Exposure_Type == "Multigenerational")
Insulin_TT_lnCVR_MG <- subset(Insulin_TT_lnCVR, Insulin_TT_lnCVR$Exposure_Type == "Multigenerational")

Insulin_FI_lnCVR_OF <- subset(Insulin_FI_lnCVR, Insulin_FI_lnCVR$Exposure_Type == "One off")
Insulin_TT_lnCVR_OF <- subset(Insulin_TT_lnCVR, Insulin_TT_lnCVR$Exposure_Type == "One off")

```

#FI Analysis
```{r}
Insulin_lnRR_FI <- rma.mv(yi, vi, random = list(~1|ES_ID,~1|Cohort_ID), data=Insulin_FI_lnRR, method = 'REML')

summary(Insulin_lnRR_FI)
funnel(Insulin_lnRR_FI)

#Tibble of overall results

Insulin_overall_lnRR_FI <- tibble(
  ID = "Overall", 
  lnRR = Insulin_lnRR_FI$b[1],
  ci.lb = Insulin_lnRR_FI$ci.lb[1],
  ci.ub = Insulin_lnRR_FI$ci.ub[1]
)

plot_Insulin_overall_FI <- ggplot(Insulin_overall_lnRR_FI, aes(x=ID, y=lnRR)) + 
  geom_errorbar(aes(ymin=ci.lb, ymax=ci.ub), width = 0, position = position_dodge(0.3)) +
  geom_point(aes(x = ID, y = lnRR), position = position_dodge(0.3))+
  geom_hline(yintercept = 0, lty = "dotted") +
  labs(x = "ID", y = "lnRR") +
  coord_flip()
plot_Insulin_overall_FI

#Split by exposure type

Insulin_overall_lnRR_FI_MG <- rma.mv(yi, vi, random = list(~1|ES_ID,~1|Cohort_ID), data=Insulin_FI_lnRR_MG, method = 'REML')

summary(Insulin_overall_lnRR_FI_MG)
funnel(Insulin_overall_lnRR_FI_MG)

Insulin_overall_lnRR_FI_OF <- rma.mv(yi, vi, random = list(~1|ES_ID,~1|Cohort_ID), data=Insulin_FI_lnRR_OF, method = 'REML')

summary(Insulin_overall_lnRR_FI_OF)
k_exp <- Insulin_FI_lnRR_OF %>% group_by(Exposure_Type) %>% count()
k_exp


funnel(Insulin_overall_lnRR_FI_OF)

Insulin_FI_Exp_lnRR <- tibble(
  Exposure_Type = c("Multigenerational","One off"),
  lnRR = c(Insulin_overall_lnRR_FI_MG$b[1],Insulin_overall_lnRR_FI_OF$b[1]),
  ci.lb = c(Insulin_overall_lnRR_FI_MG$ci.lb[1],Insulin_overall_lnRR_FI_OF$ci.lb[1]),
  ci.ub = c(Insulin_overall_lnRR_FI_MG$ci.ub[1],Insulin_overall_lnRR_FI_OF$ci.ub[1])
)

Insulin_FI_Exp_lnRR



#Plotting when split by exp type

plot_Insulin_FI_exp_type <- ggplot(Insulin_FI_Exp_lnRR, aes(x=Exposure_Type, y=lnRR, colour = Exposure_Type)) + 
  geom_errorbar(aes(ymin=ci.lb, ymax=ci.ub), width = 0.05, position = position_dodge(0.3)) +
  geom_point(aes(x = Exposure_Type, y = lnRR), position = position_dodge(0.3))+
  geom_hline(yintercept = 0, lty = "dotted") +
  labs(x = "Exp_Type", y = "lnRR") +
  coord_flip()
plot_Insulin_FI_exp_type
```

#Insulin Tolerance test results

```{r}
Insulin_lnRR_TT <- rma.mv(yi, vi, random = list(~1|ES_ID,~1|Cohort_ID), data=Insulin_TT_lnRR, method = 'REML')

summary(Insulin_lnRR_TT)
funnel(Insulin_lnRR_TT)

#Tibble of overall results

Insulin_overall_lnRR_TT <- tibble(
  ID = "Overall", 
  lnRR = Insulin_lnRR_TT$b[1],
  ci.lb = Insulin_lnRR_TT$ci.lb[1],
  ci.ub = Insulin_lnRR_TT$ci.ub[1]
)

plot_Insulin_overall_TT <- ggplot(Insulin_overall_lnRR_TT, aes(x=ID, y=lnRR)) + 
  geom_errorbar(aes(ymin=ci.lb, ymax=ci.ub), width = 0, position = position_dodge(0.3)) +
  geom_point(aes(x = ID, y = lnRR), position = position_dodge(0.3))+
  geom_hline(yintercept = 0, lty = "dotted") +
  labs(x = "ID", y = "lnRR") +
  coord_flip()
plot_Insulin_overall_TT

#Split by exposure type

Insulin_overall_lnRR_TT_MG <- rma.mv(yi, vi, random = list(~1|ES_ID,~1|Cohort_ID), data=Insulin_TT_lnRR_MG, method = 'REML')

summary(Insulin_overall_lnRR_TT_MG)
funnel(Insulin_overall_lnRR_TT_MG)

Insulin_overall_lnRR_TT_OF <- rma.mv(yi, vi, random = list(~1|ES_ID,~1|Cohort_ID), data=Insulin_TT_lnRR_OF, method = 'REML')

summary(Insulin_overall_lnRR_TT_OF)
k_exp <- Insulin_TT_lnRR_OF %>% group_by(Exposure_Type) %>% count()
k_exp

funnel(Insulin_overall_lnRR_TT_OF)

Insulin_TT_Exp_lnRR <- tibble(
  Exposure_Type = c("Multigenerational","One off"),
  lnRR = c(Insulin_overall_lnRR_TT_MG$b[1],Insulin_overall_lnRR_TT_OF$b[1]),
  ci.lb = c(Insulin_overall_lnRR_TT_MG$ci.lb[1],Insulin_overall_lnRR_TT_OF$ci.lb[1]),
  ci.ub = c(Insulin_overall_lnRR_TT_MG$ci.ub[1],Insulin_overall_lnRR_TT_OF$ci.ub[1])
)

Insulin_TT_Exp_lnRR



#Plotting when split by exp type

plot_Insulin_TT_exp_type <- ggplot(Insulin_TT_Exp_lnRR, aes(x=Exposure_Type, y=lnRR, colour = Exposure_Type)) + 
  geom_errorbar(aes(ymin=ci.lb, ymax=ci.ub), width = 0.05, position = position_dodge(0.3)) +
  geom_point(aes(x = Exposure_Type, y = lnRR), position = position_dodge(0.3))+
  geom_hline(yintercept = 0, lty = "dotted") +
  labs(x = "Exp_Type", y = "lnRR") +
  coord_flip()
plot_Insulin_TT_exp_type
```

#Fasting Insulin analysis (lnCVR)
```{r}
Insulin_lnCVR_FI <- rma.mv(yi, vi, random = list(~1|ES_ID,~1|Cohort_ID), data=Insulin_FI_lnCVR, method = 'REML')

summary(Insulin_lnCVR_FI)
funnel(Insulin_lnCVR_FI)

#Tibble of overall results

Insulin_overall_lnCVR_FI <- tibble(
  ID = "Overall", 
  lnCVR = Insulin_lnCVR_FI$b[1],
  ci.lb = Insulin_lnCVR_FI$ci.lb[1],
  ci.ub = Insulin_lnCVR_FI$ci.ub[1]
)

plot_Insulin_overall_FI_lnCVR <- ggplot(Insulin_overall_lnCVR_FI, aes(x=ID, y=lnCVR)) + 
  geom_errorbar(aes(ymin=ci.lb, ymax=ci.ub), width = 0, position = position_dodge(0.3)) +
  geom_point(aes(x = ID, y = lnCVR), position = position_dodge(0.3))+
  geom_hline(yintercept = 0, lty = "dotted") +
  labs(x = "ID", y = "lnCVR") +
  coord_flip()
plot_Insulin_overall_FI_lnCVR

#Split by exposure type

Insulin_overall_lnCVR_FI_MG <- rma.mv(yi, vi, random = list(~1|ES_ID,~1|Cohort_ID), data=Insulin_FI_lnCVR_MG, method = 'REML')

summary(Insulin_overall_lnCVR_FI_MG)
funnel(Insulin_overall_lnCVR_FI_MG)

Insulin_overall_lnCVR_FI_OF <- rma.mv(yi, vi, random = list(~1|ES_ID,~1|Cohort_ID), data=Insulin_FI_lnCVR_OF, method = 'REML')

summary(Insulin_overall_lnCVR_FI_OF)
funnel(Insulin_overall_lnCVR_FI_OF)

Insulin_FI_Exp_lnCVR <- tibble(
  Exposure_Type = c("Multigenerational", "One off"),
  lnCVR = c(Insulin_overall_lnCVR_FI_MG$b[1],Insulin_overall_lnCVR_FI_OF$b[1]),
  ci.lb = c(Insulin_overall_lnCVR_FI_MG$ci.lb[1],Insulin_overall_lnCVR_FI_OF$ci.lb[1]),
  ci.ub = c(Insulin_overall_lnCVR_FI_MG$ci.ub[1],Insulin_overall_lnCVR_FI_OF$ci.ub[1])
)

Insulin_FI_Exp_lnCVR



#Plotting when split by exp type

plot_Insulin_FI_exp_type_lnCVR <- ggplot(Insulin_FI_Exp_lnCVR, aes(x=Exposure_Type, y=lnCVR, colour = Exposure_Type)) + 
  geom_errorbar(aes(ymin=ci.lb, ymax=ci.ub), width = 0, position = position_dodge(0.3)) +
  geom_point(aes(x = Exposure_Type, y = lnCVR), position = position_dodge(0.3))+
  geom_hline(yintercept = 0, lty = "dotted") +
  labs(x = "Exp_Type", y = "lnCVR") +
  coord_flip()
plot_Insulin_FI_exp_type_lnCVR
```

#Insulin tolerance test analysis (lnCVR)
```{r}
Insulin_lnCVR_TT <- rma.mv(yi, vi, random = list(~1|ES_ID,~1|Cohort_ID), data=Insulin_TT_lnCVR, method = 'REML')

summary(Insulin_lnCVR_TT)
funnel(Insulin_lnCVR_TT)

#Tibble of overall results

Insulin_overall_lnCVR_TT <- tibble(
  ID = "Overall", 
  lnCVR = Insulin_lnCVR_TT$b[1],
  ci.lb = Insulin_lnCVR_TT$ci.lb[1],
  ci.ub = Insulin_lnCVR_TT$ci.ub[1]
)

plot_Insulin_overall_TT_lnCVR <- ggplot(Insulin_overall_lnCVR_TT, aes(x=ID, y=lnCVR)) + 
  geom_errorbar(aes(ymin=ci.lb, ymax=ci.ub), width = 0, position = position_dodge(0.3)) +
  geom_point(aes(x = ID, y = lnCVR), position = position_dodge(0.3))+
  geom_hline(yintercept = 0, lty = "dotted") +
  labs(x = "ID", y = "lnCVR") +
  coord_flip()
plot_Insulin_overall_TT_lnCVR

#Split by exposure type

Insulin_overall_lnCVR_TT_MG <- rma.mv(yi, vi, random = list(~1|ES_ID,~1|Cohort_ID), data=Insulin_TT_lnCVR_MG, method = 'REML')

summary(Insulin_overall_lnCVR_TT_MG)
funnel(Insulin_overall_lnCVR_TT_MG)

Insulin_overall_lnCVR_TT_OF <- rma.mv(yi, vi, random = list(~1|ES_ID,~1|Cohort_ID), data=Insulin_TT_lnCVR_OF, method = 'REML')

summary(Insulin_overall_lnCVR_TT_OF)
funnel(Insulin_overall_lnCVR_TT_OF)

Insulin_TT_Exp_lnCVR <- tibble(
  Exposure_Type = c("Multigenerational", "One off"),
  lnCVR = c(Insulin_overall_lnCVR_TT_MG$b[1],Insulin_overall_lnCVR_TT_OF$b[1]),
  ci.lb = c(Insulin_overall_lnCVR_TT_MG$ci.lb[1],Insulin_overall_lnCVR_TT_OF$ci.lb[1]),
  ci.ub = c(Insulin_overall_lnCVR_TT_MG$ci.ub[1],Insulin_overall_lnCVR_TT_OF$ci.ub[1])
)

Insulin_TT_Exp_lnCVR



#Plotting when split by exp type

plot_Insulin_TT_exp_type_lnCVR <- ggplot(Insulin_TT_Exp_lnCVR, aes(x=Exposure_Type, y=lnCVR, colour = Exposure_Type)) + 
  geom_errorbar(aes(ymin=ci.lb, ymax=ci.ub), width = 0.05, position = position_dodge(0.3)) +
  geom_point(aes(x = Exposure_Type, y = lnCVR), position = position_dodge(0.3))+
  geom_hline(yintercept = 0, lty = "dotted") +
  labs(x = "Exp_Type", y = "lnCVR") +
  coord_flip()
plot_Insulin_TT_exp_type_lnCVR
```



