---
title: "Leptin"
output:
  pdf_document: default
  html_document: default
---

## Meta-regression Insulin

```{r load packages, include=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(openxlsx)  
library(knitr)
library(metafor)
library(ggplot2)
library(readxl)
```

```{r}
load(file="Effect_Size_All_Traits.RData")
load(file="Effect_Size_All_Traits_lnCVR.RData")

Leptin_lnRR <- subset(Effect_Size_All_Traits, Effect_Size_All_Traits$Trait == "Leptin")
Leptin_lnCVR <- subset(Effect_Size_All_Traits_lnCVR, Effect_Size_All_Traits_lnCVR$Trait == "Leptin")

Leptin_lnRR_MG <- subset(Leptin_lnRR, Leptin_lnRR$Exposure_Type == "Multigenerational")
Leptin_lnRR_OF <- subset(Leptin_lnRR, Leptin_lnRR$Exposure_Type == "One off")

Leptin_lnCVR_MG <- subset(Leptin_lnCVR, Leptin_lnCVR$Exposure_Type == "Multigenerational")
Leptin_lnCVR_OF <- subset(Leptin_lnCVR, Leptin_lnCVR$Exposure_Type == "One off")
```
#Overall analysis
```{r}



Leptin_overall_lnRR_0mods <- rma.mv(yi, vi,random = list(~1|ES_ID,~1|Cohort_ID), data=Leptin_lnRR, method = 'REML')

#Random factors account for no independence and Cohort ID is more biologically meaningful. Can use only Cohort ID for small datasets like this

summary(Leptin_overall_lnRR_0mods)


#Tibble of overall results

Leptin_overall_lnRR <- tibble(
  ID = "Overall", 
  lnRR = 1.1962,
  ci.lb = 0.0808,
  ci.ub = 2.3115
)

plot_leptin_overall <- ggplot(Leptin_overall_lnRR, aes(x=ID, y=lnRR)) + 
  geom_errorbar(aes(ymin=ci.lb, ymax=ci.ub), width = 0, position = position_dodge(0.3)) +
  geom_point(aes(x = ID, y = lnRR), position = position_dodge(0.3))+
  geom_hline(yintercept = 0, lty = "dotted") +
  labs(title ="leptin differences, overall", x = "ID", y = "lnRR") +
  coord_flip()
plot_leptin_overall
```
#Analysis split by exposure type

```{r}
Leptin_lnRR_MG <- rma.mv(yi, vi, random = list(~1|ES_ID,~1|Cohort_ID), data=Leptin_lnRR_MG, method = 'REML')

summary(Leptin_lnRR_MG)
funnel(Leptin_lnRR_MG)

Leptin_lnRR_OF <- rma.mv(yi, vi, random = list(~1|ES_ID,~1|Cohort_ID), data=Leptin_lnRR_OF, method = 'REML')

summary(Leptin_lnRR_OF)
funnel(Leptin_lnRR_OF)

Leptin_Exp_lnRR <- tibble(
  Exposure_Type = c("Multigenerational", "One off"),
  lnRR = c(1.8529,0.1585),
  ci.lb = c(0.2579,-0.1631),
  ci.ub = c(3.4478,0.4801)
)

Leptin_Exp_lnRR



#Plotting when split by exp type

plot_Leptin_exp_type <- ggplot(Leptin_Exp_lnRR, aes(x=Exposure_Type, y=lnRR, colour = Exposure_Type)) + 
  geom_errorbar(aes(ymin=ci.lb, ymax=ci.ub), width = 0, position = position_dodge(0.3)) +
  geom_point(aes(x = Exposure_Type, y = lnRR), position = position_dodge(0.3))+
  geom_hline(yintercept = 0, lty = "dotted") +
  labs(x = "Exp_Type", y = "lnRR") +
  coord_flip()
plot_Leptin_exp_type
```

#Leptin lnCVR analysis
```{r}



Leptin_overall_lnCVR_0mods <- rma.mv(yi, vi,random = list(~1|ES_ID,~1|Cohort_ID), data=Leptin_lnCVR, method = 'REML')

#Random factors account for no independence and Cohort ID is more biologically meaningful. Can use only Cohort ID for small datasets like this

summary(Leptin_overall_lnCVR_0mods)


#Tibble of overall results

Leptin_overall_lnCVR <- tibble(
  ID = "Overall", 
  lnCVR = -0.4352,
  ci.lb = -1.2688,
  ci.ub = 0.3984
)

plot_leptin_overall_lnCVR <- ggplot(Leptin_overall_lnCVR, aes(x=ID, y=lnCVR)) + 
  geom_errorbar(aes(ymin=ci.lb, ymax=ci.ub), width = 0, position = position_dodge(0.3)) +
  geom_point(aes(x = ID, y = lnCVR), position = position_dodge(0.3))+
  geom_hline(yintercept = 0, lty = "dotted") +
  labs(title ="leptin differences, overall", x = "ID", y = "lnCVR") +
  coord_flip()
plot_leptin_overall_lnCVR
```
#Analysis split by exposure type

```{r}
Leptin_lnCVR_MG <- rma.mv(yi, vi, random = list(~1|ES_ID,~1|Cohort_ID), data=Leptin_lnCVR_MG, method = 'REML')

summary(Leptin_lnCVR_MG)
funnel(Leptin_lnCVR_MG)

Leptin_lnCVR_OF <- rma.mv(yi, vi, random = list(~1|ES_ID,~1|Cohort_ID), data=Leptin_lnCVR_OF, method = 'REML')

summary(Leptin_lnCVR_OF)
funnel(Leptin_lnCVR_OF)

Leptin_Exp_lnCVR <- tibble(
  Exposure_Type = c("Multigenerational", "One off"),
  lnCVR = c(-0.8512,0.2219),
  ci.lb = c(-2.1508,-0.1468),
  ci.ub = c(0.4483,0.5906)
)

Leptin_Exp_lnCVR



#Plotting when split by exp type

plot_Leptin_exp_type_lnCVR <- ggplot(Leptin_Exp_lnCVR, aes(x=Exposure_Type, y=lnCVR, colour = Exposure_Type)) + 
  geom_errorbar(aes(ymin=ci.lb, ymax=ci.ub), width = 0, position = position_dodge(0.3)) +
  geom_point(aes(x = Exposure_Type, y = lnCVR), position = position_dodge(0.3))+
  geom_hline(yintercept = 0, lty = "dotted") +
  labs(x = "Exp_Type", y = "lnCVR") +
  coord_flip()
plot_Leptin_exp_type_lnCVR
```

