---
title: "Main Plots"
author: "Hamza"
date: "11/23/2019"
output: html_document
---

```{r load packages, include=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(openxlsx)  
library(knitr)
library(metafor)
library(ggplot2)
library(readxl)
library(dplyr)
library(ggplot2)

#Install miktex and then run this to knit a pdf file
#install.packages('tinytex')
#tinytex::install_tinytex()
```

### Body Weight

```{r}
#Tibble
#Overall
Body_Weight_Exp_lnRR_Overall <- tibble(
  Analysis = c("Overall"),
  Percentage = c(2.48),
  ci.lb = c(0.18),
  ci.ub = c(4.82)
)

#Plotting Overall
#Plotting
plot_BW_exp_type_overall <- ggplot(Body_Weight_Exp_lnRR_Overall, aes(x=Analysis, y=Percentage)) + 
  geom_errorbar(aes(ymin=ci.lb, ymax=ci.ub), width = 0.05, position = position_dodge(0.3)) +
  geom_point(aes(x = Analysis, y = Percentage), position = position_dodge(0.3))+
  geom_hline(yintercept = 0, lty = "dotted") +
  coord_flip()
plot_BW_exp_type_overall

#Sex
Body_Weight_Exp_lnRR <- tibble(
  Analysis = c("Exposed F0","Exposed F0","Exposed F0", "Grand-offspring","Grand-offspring"),
  Sex = c("Both", "Female", "Male", "Female","Male"),
  Percentage = c(15.13,3.00,0.25,2.45,2.55),
  ci.lb = c(6.10,0.04,-3.60,-0.12,0.02),
  ci.ub = c(24.9,5.69,4.26,5.09,5.15)
)

Body_Weight_Exp_lnRR$Analysis = factor(Body_Weight_Exp_lnRR$Analysis, levels=c('Exposed F0','Grand-offspring'))

#Plotting Sex
plot_BW_exp_type <- ggplot(Body_Weight_Exp_lnRR, aes(x=Sex, y=Percentage, colour = Analysis)) + 
  geom_errorbar(aes(ymin=ci.lb, ymax=ci.ub), width = 0.05, position = position_dodge(0.3)) +
  geom_point(aes(x = Sex, y = Percentage), position = position_dodge(0.3))+
  geom_hline(yintercept = 0, lty = "dotted") +
  coord_flip()+
  facet_grid(~Analysis, space = "free_x")
plot_BW_exp_type
```

### Adiposity
```{r}
#Sex
Adiposity_Exp_lnRR <- tibble(
  Analysis = c("Exposed F0","Exposed F0", "Grand-offspring","Grand-offspring"),
  Sex = c("Female", "Male", "Female","Male"),
  Percentage = c(16.06,-0.98,4.50,25.85),
  ci.lb = c(-3.85,-40.24,-13.47,4.08),
  ci.ub = c(40.07,64.10,26.21,52.18)
)

Adiposity_Exp_lnRR$Analysis = factor(Adiposity_Exp_lnRR$Analysis, levels=c('Exposed F0','Grand-offspring'))

#Plotting Sex
plot_adiposity_exp_type <- ggplot(Adiposity_Exp_lnRR, aes(x=Sex, y=Percentage, colour = Analysis)) + 
  geom_errorbar(aes(ymin=ci.lb, ymax=ci.ub), width = 0.05, position = position_dodge(0.3)) +
  geom_point(aes(x = Sex, y = Percentage), position = position_dodge(0.3))+
  geom_hline(yintercept = 0, lty = "dotted") +
  coord_flip()+
  facet_grid(~Analysis, space = "free_x")
plot_adiposity_exp_type
```


