---
title: "Publication Bias Tests"
author: "Hamza"
date: "15 January 2020"
output:
  pdf_document: default
  html_document: default
---

```{r load packages, include=FALSE, message=FALSE, warning=FALSE}
library(tidyverse)
library(openxlsx)  
library(knitr)
library(metafor)
library(ggplot2)
library(readxl)
library(orchaRd)
library(patchwork)
library(tidyverse)
#Install miktex and then run this to knit a pdf file
#install.packages('tinytex')
#tinytex::install_tinytex()

```


### Overall lnRR and lnCVR (split by OF and MG)
```{r}
#lnRR
All_Traits_Analysis_Exp_egg <- rma.mv(yi, VmatCVR_all, mods= ~Exposure_Type-1 + sqrt(vi), random = list(~1|Paper_ID,~1|Cohort_ID,~1|ES_ID,~1|Trait), data=Effect_Size_All_Traits, method = 'REML')

summary(All_Traits_Analysis_Exp_egg)
funnel(All_Traits_Analysis_Exp_egg, yaxis = "seinv")

#lnCVR
All_Traits_Analysis_Exp_egg_lnCVR <- rma.mv(yi, vi, mods= ~Exposure_Type-1 + sqrt(vi), random = list(~1|Paper_ID,~1|Cohort_ID,~1|ES_ID,~1|Trait), data=Effect_Size_All_Traits_lnCVR, method = 'REML')

summary(All_Traits_Analysis_Exp_egg_lnCVR)
funnel(All_Traits_Analysis_Exp_egg_lnCVR, yaxis = "seinv")

#Make plots like in Shinichi's code
```

### F0 Sex and Grandoffspring Sex lnRR

```{r}
#MG F0

All_Traits_Analysis_0mods_MG_f0_egg <- rma.mv(yi, VmatCVR_MG, mods = ~F0_Parent_Exposed-1 + sqrt(vi), random = list(~1|Trait, ~1|Paper_ID,~1|Cohort_ID,~1|ES_ID), data=MG_ALL, method = 'REML')

summary(All_Traits_Analysis_0mods_MG_f0_egg) 
funnel(All_Traits_Analysis_0mods_MG_f0_egg,yaxis="seinv")

#OF F0
All_Traits_Analysis_0mods_OF_f0_egg <- rma.mv(yi, VmatCVR_OF, mods = ~F0_Parent_Exposed-1 + sqrt(vi), random = list(~1|Trait, ~1|Paper_ID,~1|Cohort_ID,~1|ES_ID), data=OF_ALL, method = 'REML')

summary(All_Traits_Analysis_0mods_OF_f0_egg)
funnel(All_Traits_Analysis_0mods_OF_f0_egg,yaxis="seinv")

#MG Sex
All_Traits_Analysis_0mods_MG_sex_egg <- rma.mv(yi, VmatCVR_MG, mods = ~Sex-1 + sqrt(vi), random = list(~1|Trait, ~1|Paper_ID,~1|Cohort_ID,~1|ES_ID), data=MG_ALL, method = 'REML')

summary(All_Traits_Analysis_0mods_MG_sex_egg)
funnel(All_Traits_Analysis_0mods_MG_sex_egg,yaxis="seinv")

#OF Sex
All_Traits_Analysis_0mods_OF_sex_egg <- rma.mv(yi, VmatCVR_OF, mods = ~Sex-1 + sqrt(vi), random = list(~1|Trait, ~1|Paper_ID,~1|Cohort_ID,~1|ES_ID), data=OF_ALL, method = 'REML')

summary(All_Traits_Analysis_0mods_OF_sex_egg)
funnel(All_Traits_Analysis_0mods_OF_sex_egg,yaxis="seinv")


```

### F0 and Offspring Sex lnCVR
```{r}
All_Traits_Analysis_0mods_MG_f0_egg_lnCVR <- rma.mv(yi, vi, mods = ~F0_Parent_Exposed-1 + sqrt(vi), random = list(~1|Trait, ~1|Paper_ID,~1|Cohort_ID,~1|ES_ID), data=MG_ALL_lnCVR, method = 'REML')

summary(All_Traits_Analysis_0mods_MG_f0_egg_lnCVR) 
funnel(All_Traits_Analysis_0mods_MG_f0_egg_lnCVR,yaxis="seinv")

#OF F0
All_Traits_Analysis_0mods_OF_f0_egg_lnCVR <- rma.mv(yi, vi, mods = ~F0_Parent_Exposed-1 + sqrt(vi), random = list(~1|Trait, ~1|Paper_ID,~1|Cohort_ID,~1|ES_ID), data=OF_ALL_lnCVR, method = 'REML')

summary(All_Traits_Analysis_0mods_OF_f0_egg_lnCVR)
funnel(All_Traits_Analysis_0mods_OF_f0_egg_lnCVR,yaxis="seinv")

#MG Sex
All_Traits_Analysis_0mods_MG_sex_egg_lnCVR <- rma.mv(yi, vi, mods = ~Sex-1 + sqrt(vi), random = list(~1|Trait, ~1|Paper_ID,~1|Cohort_ID,~1|ES_ID), data=MG_ALL_lnCVR, method = 'REML')

summary(All_Traits_Analysis_0mods_MG_sex_egg_lnCVR)
funnel(All_Traits_Analysis_0mods_MG_sex_egg_lnCVR,yaxis="seinv")

#OF Sex
All_Traits_Analysis_0mods_OF_sex_egg_lnCVR <- rma.mv(yi, vi, mods = ~Sex-1 + sqrt(vi), random = list(~1|Trait, ~1|Paper_ID,~1|Cohort_ID,~1|ES_ID), data=OF_ALL_lnCVR, method = 'REML')

summary(All_Traits_Analysis_0mods_OF_sex_egg_lnCVR)
funnel(All_Traits_Analysis_0mods_OF_sex_egg_lnCVR,yaxis="seinv")
```


### Traits lnRR and lnCVR
```{r}
#Traits MG

Traits_Analysis_MG_egg <- rma.mv(yi, VmatCVR_MG, mods = ~Trait-1 + sqrt(vi), random = list( ~1|Paper_ID,~1|Cohort_ID,~1|ES_ID), data=MG_ALL, method = 'REML')

summary(Traits_Analysis_MG_egg)
funnel(Traits_Analysis_MG_egg,yaxis="seinv")

#Traits OF

Traits_Analysis_OF_egg <- rma.mv(yi, VmatCVR_OF, mods = ~Trait-1 + sqrt(vi), random = list( ~1|Paper_ID,~1|Cohort_ID,~1|ES_ID), data=OF_ALL, method = 'REML')

summary(Traits_Analysis_OF_egg)
funnel(Traits_Analysis_OF_egg,yaxis="seinv")

#Traits MG lnCVR

Traits_Analysis_MG_egg_lnCVR <- rma.mv(yi, vi, mods = ~Trait-1 + sqrt(vi), random = list( ~1|Paper_ID,~1|Cohort_ID,~1|ES_ID), data=MG_ALL_lnCVR, method = 'REML')

summary(Traits_Analysis_MG_egg_lnCVR)
funnel(Traits_Analysis_MG_egg_lnCVR,yaxis="seinv")

#Traits OF lnCVR

Traits_Analysis_OF_egg_lnCVR <- rma.mv(yi, vi, mods = ~Trait-1 + sqrt(vi), random = list( ~1|Paper_ID,~1|Cohort_ID,~1|ES_ID), data=OF_ALL_lnCVR, method = 'REML')

summary(Traits_Analysis_OF_egg_lnCVR)
funnel(Traits_Analysis_OF_egg_lnCVR,yaxis="seinv")
```
Apply trim and fill method ? Even though we have high heterogeneity (this method involves excluding papers)


### Time lag bias - Univariate lnRR
```{r}
Time_Lag <- rma.mv(yi, vi, mods =  ~ Year, random = list(~1|Trait,~1|Paper_ID,~1|Cohort_ID,~1|ES_ID), data=Effect_Size_All_Traits, method = 'REML')

pred_time_lag_effect_uni <- predict.rma(Time_Lag)

fit_time_lag_effect <- Effect_Size_All_Traits %>% mutate(ymin = pred_time_lag_effect_uni$ci.lb, 
    ymax = pred_time_lag_effect_uni$ci.ub, ymin2 = pred_time_lag_effect_uni$cr.lb, 
    ymax2 = pred_time_lag_effect_uni$cr.ub, pred = pred_time_lag_effect_uni$pred) %>% 
    ggplot(aes(x = Year, y = yi, size = (1/ vi) + 3)) + geom_point(shape = 21, 
    fill = "grey90")+
  geom_smooth(aes(y = ymin2), method = "loess", se = FALSE, lty = "dotted", lwd = 0.25, 
    colour = "#0072B2") + geom_smooth(aes(y = ymax2), method = "loess", se = FALSE, 
    lty = "dotted", lwd = 0.25, colour = "#0072B2") + geom_smooth(aes(y = ymin), 
    method = "loess", se = FALSE, lty = "dotted", lwd = 0.25, colour = "#D55E00") + 
    geom_smooth(aes(y = ymax), method = "loess", se = FALSE, lty = "dotted", 
        lwd = 0.25, colour = "#D55E00") + geom_smooth(aes(y = pred), method = "loess", 
    se = FALSE, lty = "dashed", lwd = 0.5, colour = "black") + ylim(-1, 2) + 
    xlim(1994, 2019) + scale_x_continuous(breaks = c(1995, 2000, 2005, 2010, 
    2015, 2020)) 

fit_time_lag_effect
```

### Time lag bias - Multivariate lnRR
```{r}
Time_Lag_multi <- rma.mv(yi, vi, mods =  ~ Year + Trait + F0_Parent_Exposed + Sex + Exposure_Type, random = list(~1|Paper_ID,~1|Cohort_ID,~1|ES_ID), data=Effect_Size_All_Traits, method = 'REML')

pred_time_lag_effect_multi <- predict.rma(Time_Lag_multi)

fit_time_lag_effect_multi <- Effect_Size_All_Traits %>% mutate(ymin = pred_time_lag_effect_multi$ci.lb, 
    ymax = pred_time_lag_effect_multi$ci.ub, ymin2 = pred_time_lag_effect_multi$cr.lb, 
    ymax2 = pred_time_lag_effect_multi$cr.ub, pred = pred_time_lag_effect_multi$pred) %>% 
    ggplot(aes(x = Year, y = yi, size = (1/ vi) + 3)) + geom_point(shape = 21, 
    fill = "grey90")+
  geom_smooth(aes(y = ymin2), method = "loess", se = FALSE, lty = "dotted", lwd = 0.25, 
    colour = "#0072B2") + geom_smooth(aes(y = ymax2), method = "loess", se = FALSE, 
    lty = "dotted", lwd = 0.25, colour = "#0072B2") + geom_smooth(aes(y = ymin), 
    method = "loess", se = FALSE, lty = "dotted", lwd = 0.25, colour = "#D55E00") + 
    geom_smooth(aes(y = ymax), method = "loess", se = FALSE, lty = "dotted", 
        lwd = 0.25, colour = "#D55E00") + geom_smooth(aes(y = pred), method = "loess", 
    se = FALSE, lty = "dashed", lwd = 0.5, colour = "black") + ylim(-1, 2) + 
    xlim(1994, 2019) + scale_x_continuous(breaks = c(1995, 2000, 2005, 2010, 
    2015, 2020)) 

fit_time_lag_effect_multi
```


### Calculating how many papers use same control animals (per trait)
```{r}
Papers_Controls <- ALL_TRAITS %>% group_by(Cohort_ID)  %>% count(Control_ID)
Papers_Controls
```






