---
title: "Research Questions"
author: "Hamza"
date: "17 September 2019"
output: html_document
---

```{r load packages, include=FALSE}

library(tidyverse)
library(openxlsx)  
library(knitr)
library(metafor)
library(ggplot2)
```

# Research Questions
```{r}
# Research Questions 

#1. What is the overall effect of exposure of F0 generation to obesogenic diets on F2 and F3 (if applicable) offspring? 
#2.	What is the overall effect of continuous multigenerational exposure to obesogenic diets on generations F2, F3? 
#3.	Are the effects of exposure of F0 generation to obesogenic diets on F2 and F3 offspring different between #paternal and maternal F0 exposure lines? 
#4.	Are the effects of exposure of F0 generation to obesogenic diets on F2 and F3 generations different between female and male offspring?
#5.	Which traits are the most affected in F2 and subsequent generations?

#For each of the questions listed above, we will look at the effects on both trait means and variability, comparing control and treatment groups at each generation.

```

# Question 1
```{r}

## (lnRR)

Effect_Size_All_Traits <- escalc(measure="ROM", m1i=Mean_Treatment, sd1i=SD_Treatment, n1i=Sample_Size_n_Treatment, m2i=Mean_Control, sd2i=SD_Control, n2i=Sample_Size_n_Control, data=ALL_TRAITS)

write.csv(Effect_Size_All_Traits, file = "es.csv")

hist(Effect_Size_All_Traits$yi)
hist(log(Effect_Size_All_Traits$vi))
```

```{r}
# Modelling all traits with no mods (lnRR)
All_Traits_Analysis_0mods <- rma.mv(yi, vi, random = list(~1|Trait, ~1|Paper_ID,~1|Cohort_ID), data=Effect_Size_All_Traits, method = 'REML')

summary(All_Traits_Analysis_0mods)
```

```{r}
# Modelling all traits exposure type (lnRR)

All_Traits_Analysis_mods <- rma.mv(yi, vi, mods = ~Exposure_Type, random = list(~1|Trait,~1|Paper_ID,~1|Cohort_ID), data=Effect_Size_All_Traits, method = 'REML')

summary(All_Traits_Analysis_mods)

```

```{r}
# Intercept only model (lnRR)
All_Traits_Analysis <- rma.mv(yi, vi, mods = ~relevel(Exposure_Type, ref="One off")-1, random = list(~1|Trait, ~1|Paper_ID,~1|Cohort_ID), data=Effect_Size_All_Traits, method = 'REML')

summary(All_Traits_Analysis)
```

```{r}
# lnCVR
Effect_Size_All_Traits_lnCVR <- escalc(measure="CVR", m1i=Mean_Treatment, sd1i=SD_Treatment, n1i=Sample_Size_n_Treatment, m2i=Mean_Control, sd2i=SD_Control, n2i=Sample_Size_n_Control, data=ALL_TRAITS)

hist(Effect_Size_All_Traits_lnCVR$yi)
hist(log(Effect_Size_All_Traits_lnCVR$vi))
```

```{r}
# Modelling all traits with no mods (lnCVR)
All_Traits_Analysis_0mods_lnCVR <- rma.mv(yi, vi, random = list(~1|Trait, ~1|Paper_ID,~1|Cohort_ID), data=Effect_Size_All_Traits_lnCVR, method = 'REML')

summary(All_Traits_Analysis_0mods_lnCVR)
```

```{r}
# Modelling all traits exposure type (lnCVR)

All_Traits_Analysis_mods_lnCVR <- rma.mv(yi, vi, mods = ~relevel(Exposure_Type, ref="One off"), random = list(~1|Trait, ~1|Paper_ID,~1|Cohort_ID), data=Effect_Size_All_Traits_lnCVR, method = 'REML')

summary(All_Traits_Analysis_mods_lnCVR)
```

# Question 2

```{r}
#lnRR
All_Traits_Analysis_MG <- rma.mv(yi, vi, mods = ~relevel(Exposure_Type, ref="Multigenerational"), random = list(~1|Trait, ~1|Paper_ID,~1|Cohort_ID), data=Effect_Size_All_Traits, method = 'REML')

summary(All_Traits_Analysis_MG)

```
```{r}
#lnCVR

All_Traits_Analysis_lnCVR_MG <- rma.mv(yi, vi, mods = ~relevel(Exposure_Type, ref="Multigenerational"), random = list(~1|Trait, ~1|Paper_ID,~1|Cohort_ID), data=Effect_Size_All_Traits_lnCVR, method = 'REML')

summary(All_Traits_Analysis_lnCVR_MG)
```

# Question 3
```{r}
#lnRR
All_Traits_Analysis_F0_Parents <- rma.mv(yi, vi, mods = ~relevel(F0_Parent_Exposed, ref="Female"), random = list(~1|Trait, ~1|Paper_ID,~1|Cohort_ID), data=Effect_Size_All_Traits, method = 'REML')

summary(All_Traits_Analysis_F0_Parents)
```
```{r}
#lnCVR

All_Traits_Analysis_lnCVR_F0_Parents <- rma.mv(yi, vi, mods = ~relevel(F0_Parent_Exposed, ref="Female"), random = list(~1|Trait, ~1|Paper_ID,~1|Cohort_ID), data=Effect_Size_All_Traits_lnCVR, method = 'REML')

summary(All_Traits_Analysis_lnCVR_F0_Parents)
```

# Question 4
```{r}
#lnRR
All_Traits_Analysis_Sex <- rma.mv(yi, vi, mods = ~relevel(Sex, ref="Female"), random = list(~1|Trait, ~1|Paper_ID,~1|Cohort_ID), data=Effect_Size_All_Traits, method = 'REML')

summary(All_Traits_Analysis_Sex)
```

```{r}
#lnCVR

All_Traits_Analysis_lnCVR_Sex <- rma.mv(yi, vi, mods = ~relevel(Sex, ref="Female"), random = list(~1|Trait, ~1|Paper_ID,~1|Cohort_ID), data=Effect_Size_All_Traits_lnCVR, method = 'REML')

summary(All_Traits_Analysis_lnCVR_Sex)
```

```{r}
MG_ALL$Trait <- factor(MG_ALL$Trait)
MG_ALL$Exposure_Type <- factor(MG_ALL$Exposure_Type)
MG_ALL$Sex <- factor(MG_ALL$Sex)
MG_ALL$Generation <- factor(MG_ALL$Generation)
MG_ALL$Cohort_ID <- factor(MG_ALL$Cohort_ID)
MG_ALL$Paper_ID <- factor(MG_ALL$Paper_ID)
MG_ALL$Rodent_type <- factor(MG_ALL$Rodent_type)
MG_ALL$F2_Diet_at_measurement <- factor(MG_ALL$F2_Diet_at_measurement)
MG_ALL$Strain <- factor(MG_ALL$Strain)
MG_ALL$F0_Parent_Exposed <- factor(MG_ALL$F0_Parent_Exposed)



```

```{r}
OF_ALL$Trait <- factor(OF_ALL$Trait)
OF_ALL$Exposure_Type <- factor(OF_ALL$Exposure_Type)
OF_ALL$Sex <- factor(OF_ALL$Sex)
OF_ALL$Generation <- factor(OF_ALL$Generation)
OF_ALL$Cohort_ID <- factor(OF_ALL$Cohort_ID)
OF_ALL$Paper_ID <- factor(OF_ALL$Paper_ID)
OF_ALL$Rodent_type <- factor(OF_ALL$Rodent_type)
OF_ALL$F2_Diet_at_measurement <- factor(OF_ALL$F2_Diet_at_measurement)
OF_ALL$Strain <- factor(OF_ALL$Strain)
OF_ALL$F0_Parent_Exposed <- factor(OF_ALL$F0_Parent_Exposed)

```



# **2. overall analysis splitting by exposure type (log response ratio)**
```{r}
# Modelling all traits with no mods (lnRR)
All_Traits_Analysis_0mods_MG <- rma.mv(yi, vi, random = list(~1|Trait, ~1|Paper_ID,~1|Cohort_ID), data=MG_ALL, method = 'REML')


All_Traits_Analysis_0mods_OF <- rma.mv(yi, vi, random = list(~1|Trait, ~1|Paper_ID,~1|Cohort_ID), data=OF_ALL, method = 'REML')

#Adding moderators
All_Traits_Analysis_0mods_MG_f0 <- rma.mv(yi, vi, mods = ~F0_Parent_Exposed, random = list(~1|Trait, ~1|Paper_ID,~1|Cohort_ID), data=MG_ALL, method = 'REML')

summary(All_Traits_Analysis_0mods_MG_f0)


All_Traits_Analysis_0mods_OF_f0 <- rma.mv(yi, vi, mods = ~F0_Parent_Exposed, random = list(~1|Trait, ~1|Paper_ID,~1|Cohort_ID), data=OF_ALL, method = 'REML')

summary(All_Traits_Analysis_0mods_OF_f0)

All_Traits_Analysis_0mods_MG_rodent <- rma.mv(yi, vi, mods = ~Rodent_type, random = list(~1|Trait, ~1|Paper_ID,~1|Cohort_ID), data=MG_ALL, method = 'REML')

summary(All_Traits_Analysis_0mods_MG_rodent)


All_Traits_Analysis_0mods_OF_rodent <- rma.mv(yi, vi, mods = ~Rodent_type, random = list(~1|Trait, ~1|Paper_ID,~1|Cohort_ID), data=OF_ALL, method = 'REML')

summary(All_Traits_Analysis_0mods_OF_rodent)

All_Traits_Analysis_0mods_MG_sex <- rma.mv(yi, vi, mods = ~Sex, random = list(~1|Trait, ~1|Paper_ID,~1|Cohort_ID), data=MG_ALL, method = 'REML')

summary(All_Traits_Analysis_0mods_MG_sex)


All_Traits_Analysis_0mods_OF_sex <- rma.mv(yi, vi, mods = ~Sex, random = list(~1|Trait, ~1|Paper_ID,~1|Cohort_ID), data=OF_ALL, method = 'REML')

summary(All_Traits_Analysis_0mods_OF_sex)

All_Traits_Analysis_0mods_MG_age <- rma.mv(yi, vi, mods = ~Age_Days, random = list(~1|Trait, ~1|Paper_ID,~1|Cohort_ID), data=MG_ALL, method = 'REML')

summary(All_Traits_Analysis_0mods_MG_age)


All_Traits_Analysis_0mods_OF_age <- rma.mv(yi, vi, mods = ~Age_Days, random = list(~1|Trait, ~1|Paper_ID,~1|Cohort_ID), data=OF_ALL, method = 'REML')

summary(All_Traits_Analysis_0mods_OF_age)
```

# **Summary table and figures**
```{r}
# Making a table of meta-analytic results for ln_RR

experiment_type_overall <- c(rep("OF", 5), rep("MG", 5))

mod_type <- rep(c("Overall", "F0 Parent", "Rodent", "Sex", "Age"), 2)  

lnRR_MA_means_overall <- c(All_Traits_Analysis_0mods_MG$b, All_Traits_Analysis_0mods_OF$b, All_Traits_Analysis_0mods_MG_f0$b, All_Traits_Analysis_0mods_OF_f0$b, All_Traits_Analysis_0mods_MG_rodent$b, All_Traits_Analysis_0mods_OF_rodent$b, All_Traits_Analysis_0mods_MG_sex$b, All_Traits_Analysis_0mods_OF_sex$b, All_Traits_Analysis_0mods_MG_age$b, All_Traits_Analysis_0mods_OF_age$b)

lnRR_MA_means

lnRR_MA_cilb_overall <- c(All_Traits_Analysis_0mods_MG$ci.lb, All_Traits_Analysis_0mods_OF$ci.lb, All_Traits_Analysis_0mods_MG_f0$ci.lb, All_Traits_Analysis_0mods_OF_f0$ci.lb, All_Traits_Analysis_0mods_MG_rodent$ci.lb, All_Traits_Analysis_0mods_OF_rodent$ci.lb, All_Traits_Analysis_0mods_MG_sex$ci.lb, All_Traits_Analysis_0mods_OF_sex$ci.lb, All_Traits_Analysis_0mods_MG_age$ci.lb, All_Traits_Analysis_0mods_OF_age$ci.lb)

lnRR_MA_cilb_overall

lnRR_MA_ciuci.uci.uci.ub <- c(All_Traits_Analysis_0mods_MG$ci.ub, All_Traits_Analysis_0mods_OF$ci.ub, All_Traits_Analysis_0mods_MG_f0$ci.ub, All_Traits_Analysis_0mods_OF_f0$ci.ub, All_Traits_Analysis_0mods_MG_rodent$ci.ub, All_Traits_Analysis_0mods_OF_rodent$ci.ub, All_Traits_Analysis_0mods_MG_sex$ci.ub, All_Traits_Analysis_0mods_OF_sex$ci.ub, All_Traits_Analysis_0mods_MG_age$ci.ub, All_Traits_Analysis_0mods_OF_age$ci.ub)

lnRR_MA_ciub_overall

lnRR_MA_k_overall <- c(All_Traits_Analysis_0mods_MG$k, All_Traits_Analysis_0mods_OF$k, All_Traits_Analysis_0mods_MG_f0$k, All_Traits_Analysis_0mods_OF_f0$k, All_Traits_Analysis_0mods_MG_rodent$k, All_Traits_Analysis_0mods_OF_rodent$k, All_Traits_Analysis_0mods_MG_sex$k, All_Traits_Analysis_0mods_OF_sex$k, All_Traits_Analysis_0mods_MG_age$k, All_Traits_Analysis_0mods_OF_age$k)

lnRR_MA_k_overall

length(OF_lnRR_BW_MA$s.levels[1][[1]])

lnRR_MA_mods_overall <- c(length(All_Traits_Analysis_0mods_MG$s.levels[1][[1]]), 
                     length(All_Traits_Analysis_0mods_OF$s.levels[1][[1]]),
                     length(All_Traits_Analysis_0mods_MG_f0$s.levels[1][[1]]),
                     length(All_Traits_Analysis_0mods_OF_f0$s.levels[1][[1]]),
                     length(All_Traits_Analysis_0mods_MG_rodent$s.levels[1][[1]]),
                     length(All_Traits_Analysis_0mods_OF_rodent$s.levels[1][[1]]),
                     length(All_Traits_Analysis_0mods_MG_sex$s.levels[1][[1]]),
                     length(All_Traits_Analysis_0mods_OF_sex$s.levels[1][[1]]),
                     length(All_Traits_Analysis_0mods_MG_age$s.levels[1][[1]]),
                     length(All_Traits_Analysis_0mods_OF_age$s.levels[1][[1]])
                     )
                     
lnRR_MA_mods_overall

lnRR_MA_papers_overall <- c(length(All_Traits_Analysis_0mods_MG$s.levels[2][[1]]), 
                     length(All_Traits_Analysis_0mods_OF$s.levels[2][[1]]),
                     length(All_Traits_Analysis_0mods_MG_f0$s.levels[2][[1]]),
                     length(All_Traits_Analysis_0mods_OF_f0$s.levels[2][[1]]),
                     length(All_Traits_Analysis_0mods_MG_rodent$s.levels[2][[1]]),
                     length(All_Traits_Analysis_0mods_OF_rodent$s.levels[2][[1]]),
                     length(All_Traits_Analysis_0mods_MG_sex$s.levels[2][[1]]),
                     length(All_Traits_Analysis_0mods_OF_sex$s.levels[2][[1]]),
                     length(All_Traits_Analysis_0mods_MG_age$s.levels[2][[1]]),
                     length(All_Traits_Analysis_0mods_OF_age$s.levels[2][[1]])
                     )
                     
lnRR_MA_papers_overall

lnRR_MA_Ncohorts_overall <- c(length(All_Traits_Analysis_0mods_MG$s.levels[3][[1]]), 
                     length(All_Traits_Analysis_0mods_OF$s.levels[3][[1]]),
                     length(All_Traits_Analysis_0mods_MG_f0$s.levels[3][[1]]),
                     length(All_Traits_Analysis_0mods_OF_f0$s.levels[3][[1]]),
                     length(All_Traits_Analysis_0mods_MG_rodent$s.levels[3][[1]]),
                     length(All_Traits_Analysis_0mods_OF_rodent$s.levels[3][[1]]),
                     length(All_Traits_Analysis_0mods_MG_sex$s.levels[3][[1]]),
                     length(All_Traits_Analysis_0mods_OF_sex$s.levels[3][[1]]),
                     length(All_Traits_Analysis_0mods_MG_age$s.levels[3][[1]]),
                     length(All_Traits_Analysis_0mods_OF_age$s.levels[3][[1]])
                     )
                     
lnRR_MA_Ncohorts_overall  

#create data fame
lnRR_MA_results <- data.frame(Experiment_type = experiment_type, trait = trait_type, mean = lnRR_MA_means, ci.lb= lnRR_MA_cilb, ci.ub= lnRR_MA_ciub, k= lnRR_MA_k, N_papers = lnRR_MA_Npapers, N_cohorts=lnRR_MA_Ncohorts)

lnRR_MA_results

lnRR_MA_results <- unite(lnRR_MA_results, "labels", c("Experiment_type", "trait"), sep = " - ", remove = FALSE)

lnRR_MA_results

#Plotting

plot_lnRR <- ggplot(lnRR_MA_results, aes(x=trait, y=mean, colour=Experiment_type)) + 
  geom_errorbar(aes(ymin=ci.lb, ymax=ci.ub), width = 0, position = position_dodge(0.3)) +
  geom_point(aes(x = trait, y = mean), position = position_dodge(0.3))+
  geom_hline(yintercept = 0, lty = "dotted") +
  labs(title ="Difference between treatment and control in means", x = "Traits", y = "lnRR") +
  coord_flip()
 
plot_lnRR

ggsave("../figs/plot_lnRR.png")

```




